### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by WuYuZh17** [ANA-Training-2024/setup#1]
连接教学机器时报了kex_exchange_identification: read: Connection reset
连接详情如下：
<img width="581" alt="屏幕截图 2024-10-07 131648" src="https://github.com/user-attachments/assets/400f34f3-1ed2-4d3a-947e-9d5f8486cfe2">
不知道为什么服务器没过，是不是我打错（或者理解错了）账号名的意思，谢谢！

**Comment by abdtyx** [comment]
服务器暂未开放，请耐心等待
