### ISSUE TITLE
gcc的安装问题以及学习机器

### ISSUE THREAD

**Issue by mark4871** [ANA-Training-2024/setup#10]
1、请问一下gcc怎么在Windows上安装呢？网上的教程好像都是关于mingw的😓。
2、教学机器什么时候能够连接呢？

**Comment by Dt8333** [comment]
1. Mingw是GCC在Windows上的一个实现。你可以使用它来编译C程序，用于前面任务的执行。但可能后续任务中涉及Linux API的程序无法编译。
2. 出错了，但我们做对了。请坐和放宽，耐心等待。

**Comment by Su-Jiaqi** [comment]
如果下载了c，应该是不需要安装gcc的，关注一下环境变量

**Comment by mark4871** [comment]
> 如果下载了c，应该是不需要安装gcc的，关注一下环境变量

下载C,这个C是指C语言IDE吗?还是？

**Comment by Su-Jiaqi** [comment]
你用的是什么操作系统和写代码的软件？是直接用终端还是下载了vscode

**Comment by mark4871** [comment]
> 你用的是什么操作系统和写代码的软件？是直接用终端还是下载了vscode

我电脑是Windows11操作系统，IDE我之前用的是vs，这几天下载了vscode.
不好意思，今天白天课挺多的，现在才看到。

**Comment by mark4871** [comment]
> 你用的是什么操作系统和写代码的软件？是直接用终端还是下载了vscode

如果下载了vscode,是可以导入gcc到命令行里吗？

**Comment by Dt8333** [comment]
windows不自带gcc。
你可以通过：
1. 安装Mingw使用gcc
2. 或者在你的Develop command prompt for VS中输入code以在code中使用msvc
3. 或者使用VS来直接调用msvc
4. 安装WSL并使用vscode连接到WSL以调用WSL内置的gcc

以上方法来编译程序
