### ISSUE TITLE
关于gcc及其使用

### ISSUE THREAD

**Issue by RevengeBugle** [ANA-Training-2024/setup#12]
安装了MinGW gcc版本4.8.1
如图，在执行编译命令时未报错也未输出结果
并且也没有生成可执行文件，具体表现为终端找不到可执行文件，并且我打开资源管理器检查后也没有发现可执行文件
![image](https://github.com/user-attachments/assets/3947ceeb-ca43-4118-b440-08383e5cee8f)
请问：
1.出现这种情况是否是gcc出了问题？应当如何解决？
2.使用gcc进行编译并试运行检查是否是考核的一部分？在时间紧张的情况下可否使用devC++这种自带编译器的编辑器进行编译运行和检查？

**Comment by Su-Jiaqi** [comment]
ls一下，看看你的目录下多了什么。windows的可执行文件后缀应该是.exe

**Comment by Su-Jiaqi** [comment]
如果你想要指定输出文件，采用  `gcc ex1.c -o ex1.exe`

**Comment by RevengeBugle** [comment]
> ls一下，看看你的目录下多了什么。windows的可执行文件后缀应该是.exe

已操作，没有发现多了什么，目录下全部是.c文件

**Comment by Su-Jiaqi** [comment]
你这个是windows的操作系统吗

**Comment by RevengeBugle** [comment]
> 你这个是windows的操作系统吗

是的

**Comment by Su-Jiaqi** [comment]
gcc进行编译并试运行检查不是考核的一部分，如果你能正确运行代码，不强求采用gcc。但是在日后的编程中，gcc是一种非常重要的编译方式，强烈推荐学会

**Comment by Su-Jiaqi** [comment]
你的电脑是否有git bash，如果有，请采用git bash尝试。git bash可以看出来每一步是否执行成功。
之后再执行一下刚刚说到的给gcc后加-o参数定输出的命令

**Comment by Su-Jiaqi** [comment]
还有，你确信你的代码可以正确编译吗？如果编译失败，powershell上不会显示，但是不会有输出文件

**Comment by Su-Jiaqi** [comment]
对于dev，更推荐使用vscode。除了插件方便实用，后续在连接远程服务器（现在教学服务器已开放）时和dev相比有绝对优势

**Comment by RevengeBugle** [comment]
> 还有，你确信你的代码可以正确编译吗？如果编译失败，powershell上不会显示，但是不会有输出文件

将代码复制到devc++内可以成功编译运行，只在vscode内不行，此外采用git bash尝试后仍为同样的结果，如图，ls后什么都没有多出来
![image](https://github.com/user-attachments/assets/2e074c96-9388-4e4a-bbbb-b3e424fee461)
zhe'shi这是devc++内编译运行的结果
![image](https://github.com/user-attachments/assets/3a29a659-19ad-456f-b0af-bca3781e58f3)

**Comment by Dt8333** [comment]
请执行`gcc --version`查看是否能输出gcc版本。
如果不能请检查Mingw安装与环境变量PATH。
Dev CPP中实际调用的是其附带的Mingw。你可以在编译器设置中看到相关信息。

**Comment by Su-Jiaqi** [comment]
vscode编译+运行需要写配置文件，详情可以自己上网搜索
建议配置好。因为之后写task需要用vscode连远程服务器，大概率是需要debug的，一遍写好几乎不可能
