### ISSUE TITLE
关于malloc函数

### ISSUE THREAD

**Issue by RevengeBugle** [ANA-Training-2024/setup#13]
叠甲：本人已详细查阅setup文档，发现“询问完成task途中遇到的问题”并不在“你不可以做的事”之列，并且本人自认为在这个问题中没有透露ex的答案；此外由于gcc暂时没有配置好所以使用的是devcpp进行编译运行，不保证现象完全和gcc的一样。
ex5中用到了malloc函数，原题是直接使用malloc()，但是由于本人太菜事先不会相关语法，所以上网搜索发现malloc需要配合数据类型强制转换形式诸如(type)malloc(...)使用，并且经过试验，直接按照ex5中的写法会发生编译错误。错误如下图：
![image](https://github.com/user-attachments/assets/8089234b-bbf2-4a2e-a3cd-6a9fa48b5f12)
"to" 后面的内容不截下来是有意的，因为这可能涉及到答案。
请问：
1.这种现象是何原因？
2.显然ex不允许我们修改下划线以外的部分，是否应该硬着头皮按照原ex的方式写？

**Comment by RevengeBugle** [comment]
PS:追加一个问题：教学中明确提到了数组可以比其存储的字符串更大，这是否意味着无需详细计算所需内存大小而随便填一个很大的数也可以完成ex？还是说必须严格分配所需的内存？

**Comment by Dt8333** [comment]
叠甲：本人已4年未使用DevCPP，无法保证以下内容完全正确。请再次检查或验证以下说法。
根据报错内容，我猜你的DevCPP可能是使用了g++编译而不是gcc。请手动切换到DevCPP根目录下找到其附带的Mingw并手动用gcc编译尝试。

**Comment by RevengeBugle** [comment]
请注意
你的连接器命令行中添加了libstdc++
这将使gcc默认以c++规则编译
请移除该参数后再次尝试

**Comment by Dt8333** [comment]
> PS:追加一个问题：教学中明确提到了数组可以比其存储的字符串更大，这是否意味着无需详细计算所需内存大小而随便填一个很大的数也可以完成ex？还是说必须严格分配所需的内存？

理论上是。
实际上应该会有一个限制来防止一些破坏行为。
我不确定该限制是否与任务描述一致。

**Comment by Dt8333** [comment]
啊非常抱歉点回复误触到了修改。
请谅解

**Comment by abdtyx** [comment]
在C语言中动态内存分配必须使用malloc，你为了使你的代码在devcpp上通过编译，使用了C++的new语法。然而评测机使用gcc编译你的代码，因此导致编译不通过，测试点0分。

**Comment by abdtyx** [comment]
ex5错在"compute the address of the element at index 2 (0-indexed)"

**Comment by abdtyx** [comment]
ex6第27行编译错误
ex9在创建student2时使用了错误的方法

**Comment by RevengeBugle** [comment]
> ex6第27行编译错误 ex9在创建student2时使用了错误的方法

已收到提示并急速改进，现80分，请问能否提供ex10Fail的有关线索？
