### ISSUE TITLE
连接不上

### ISSUE THREAD

**Issue by hua293** [ANA-Training-2024/setup#14]
![image](https://github.com/user-attachments/assets/1b27e889-7376-4711-b254-4ab37b39822b)

**Comment by Dt8333** [comment]
不好说…
试试加个参数 ` -p 443` ？

**Comment by abdtyx** [comment]
疑似网络故障。
ps: github使用22端口进行ssh连接，而不是443

**Comment by Dt8333** [comment]
https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port
Github有提供使用443端口ssh访问的方法。
