### ISSUE TITLE
关于task2的内存限制

### ISSUE THREAD

**Issue by RevengeBugle** [ANA-Training-2024/setup#16]
根据题目数据范围，n<=2x10^7
按照正常思路（指大多数正常人首先想到的）
我们至少需要使用大小超过2x10^7个元素的数组来存储ai，并且可以从数据范围推出合适的数据类型来声明ai数组
但是根据计算 仅这一个ai数组的内存占用就高达160,000,000字节，合152.59MB，已经超过128MB的限制
显然通过一些方式可以优化内存占用，使其远低于128MB，但是本人认为这需要一些诸如竞赛经历之类的先导知识，对于纯小白不是很友好（虽然可能只有个别分数需要优化来达到）
因此，建议扩大task2的内存限制，使其的解法变得更加显然。如果是因为鄙人错误的计算导致这个乌龙，抑或是讨论优化算法是考核的一部分，请忽略这个issue。
PS：gradescope炸了所以暂时没法验证鄙人想到的优化方法的可行性，不排除压根不存在这种方法只是我多想了的情况（）

**Comment by RevengeBugle** [comment]
好吧优化算法也炸了，我太菜了（）
正在努力寻找正确的方法

**Comment by HT4w5** [comment]
有更好的方法，但是我也不能全过（

**Comment by RevengeBugle** [comment]
已经成功实现O(m)的空间复杂度，但由于题目中没给m的范围（只给了min(m,n-m)的范围），可能还是超过限制（

**Comment by RevengeBugle** [comment]
突然想到了一个O(1)空间复杂度的算法，但是这个算法貌似和queue无关（可能利用了它的思想？
待我测试

**Comment by RevengeBugle** [comment]
> 突然想到了一个O(1)空间复杂度的算法，但是这个算法貌似和queue无关（可能利用了它的思想？ 待我测试

是我想多了，这个算法无法实现（

**Comment by abdtyx** [comment]
> 但是根据计算 仅这一个ai数组的内存占用就高达160,000,000字节，合152.59MB，已经超过128MB的限制

You are right. But we can't expand the memory limits because this is exactly why it should be 128MB.
Hint: If you don't need **it**, then don't put **it** in your memory :-)
