### ISSUE TITLE
提问task3相关

### ISSUE THREAD

**Issue by WindXyloper** [ANA-Training-2024/setup#18]
打开文件的时候发现
无法打开 源 文件 "arpa/inet.h"
无法打开 源 文件 "netdb.h"
无法打开 源 文件 "netinet/in.h"
无法打开 源 文件 "sys/socket.h"
这几个看起来不像标准库啊，请问这几个库是怎么来的，还有怎么下载

**Comment by Dt8333** [comment]
请确认您在Linux GCC下编译。
本任务不支持Windows。

**Comment by WindXyloper** [comment]
好的
