### ISSUE TITLE
course entry code 获取方法以及教学机器访问

### ISSUE THREAD

**Issue by HiSysCore** [ANA-Training-2024/setup#19]
处于一些愚蠢的原因，我直到昨天才加入考核群，请问我该如何获取我的course entry code
又及：我是否需要在linux的terminal下用ssh连接教学机器，还是说可以在windows的cmd中连接

**Comment by HiSysCore** [comment]
我已经解决了第二个问题，我现在只需要获取course entry code,感谢

**Comment by Dt8333** [comment]
Course entry code应该在群公告中有提供。请查看历史群公告。

**Comment by HiSysCore** [comment]
好的，感谢
