### ISSUE TITLE
无法注册

### ISSUE THREAD

**Issue by chaoment** [ANA-Training-2024/setup#2]
![屏幕截图 2024-10-07 150508](https://github.com/user-attachments/assets/d5e6b3b1-397f-45e3-97d8-4868c8ba01d6)
在创建Gradescope账号时出现了如图所示的报错，不知道是什么原因。

还有在登陆task1时显示页面不存在，我没有接受邀请，请问在哪里接受，谢谢！
![屏幕截图 2024-10-07 151002](https://github.com/user-attachments/assets/c7692260-7955-4477-aba7-60f3b4ab9599)

**Comment by abdtyx** [comment]
Gradescope注册时请输入学校
Backend仓库现已发出邀请

**Comment by Dt8333** [comment]
Close as completed.
