### ISSUE TITLE
请问该在哪里找到我的student仓库

### ISSUE THREAD

**Issue by HiSysCore** [ANA-Training-2024/setup#20]
我好像没有在邮箱里找到我的student仓库邀请，我需要找管理员重新申请一个吗

**Comment by Dt8333** [comment]
请修改你的群名片。确认身份后会为你新建仓库。

**Comment by Durandler** [comment]
感谢，我的群名片为 黄思晨 galaxy2006

**Comment by Durandler** [comment]
> 请修改你的群名片。确认身份后会为你新建仓库。
感谢，我的群名片为 黄思晨 galaxy2006

**Comment by Dt8333** [comment]
已经向galaxy2006发送邀请。请检查电子邮件。
如果galaxy2006不是你，修改群名片为你的姓名+Github用户名。
由于个人信息泄露，将删除上面回复。

**Comment by HiSysCore** [comment]
> 已经向galaxy2006发送邀请。请检查电子邮件。 如果galaxy2006不是你，修改群名片为你的姓名+Github用户名。 由于个人信息泄露，将删除上面回复。

抱歉，我之前的群名片使用了gradescope的id，我现在重新更改了群名片(Durandler)

**Comment by Dt8333** [comment]
已确认
将收回galaxy2006的权限并为Durandler添加权限。
请在10mins后检查邮箱并接受邀请。

**Comment by HiSysCore** [comment]
已接收邀请，感谢帮助
