### ISSUE TITLE
遇到了空白文件

### ISSUE THREAD

**Issue by HiSysCore** [ANA-Training-2024/setup#22]
我在进行ex3_pointers_and_functions.c时，使用nano将其打开，发现呈现空白内容
请问我该怎样获取所需的文件
![ts1_1](https://github.com/user-attachments/assets/97a1faae-7409-47d8-8479-d3a3de4c7f71)
![ts1_2](https://github.com/user-attachments/assets/da9ef8bd-d0d8-4e10-a832-0f9914d13304)

**Comment by Dt8333** [comment]
请使用ls命令列出文件并仔细检查文件名。
你输入给nano的文件名有误。
建议善用Tab自动补全文件名，防止出现错误。

**Comment by HiSysCore** [comment]
问题已解决，感谢
