### ISSUE TITLE
Don't have a student repo yet.

### ISSUE THREAD

**Issue by HT4w5** [ANA-Training-2024/setup#4]
Hi, not sure if I'm being too anxious, but I still don't have a student repo yet. I'd be thankful If you could kindly create one.

**Comment by abdtyx** [comment]
![图片](https://github.com/user-attachments/assets/ba9b559b-e797-4ba8-9ceb-2cfb5b698130)
We had already invited you to student7. Please check your invitation inbox.

**Comment by HT4w5** [comment]
Sorry, I have found it now. Thanks.
