### ISSUE TITLE
gradescope 中找不到自己的 student 仓库

### ISSUE THREAD

**Issue by WellDown64** [ANA-Training-2024/setup#5]
我在自己的student仓库中commit了代码，在github中能看到提交，但是在gradescope中找不到我的student仓库，图里往下翻也没找到。
图中test-git是我的私有仓库，Xjtuse-Guide是我fork的一个公有仓库，ANA-IBD/student12是上学期后端开发导论的仓库，这些都可以被gradescope识别。
![image](https://github.com/user-attachments/assets/b43c777b-540c-4b38-9cb1-0c5a6274f8b9)

**Comment by Dt8333** [comment]
Hello WellDown64,

请前往 https://github.com/settings/applications
选择Gradescope
在Organization access中Request ANA-Training-2024的权限
我们会处理您的申请，通过后即可访问您的Repo.

Best Regard,
Dale

**Comment by WellDown64** [comment]
我什么都没做，但是这里显示access request pending, 这是已经在申请了吗
![image](https://github.com/user-attachments/assets/8e550221-d275-4b7d-b933-c8e373c21e2d)

**Comment by abdtyx** [comment]
Access granted，现在应该能提交了

**Comment by WellDown64** [comment]
现在好了，感谢
