### ISSUE TITLE
提交问题

### ISSUE THREAD

**Issue by hua293** [ANA-Training-2024/setup#7]
![1c0056becbb35220c93739ca2a5c0904](https://github.com/user-attachments/assets/8e92b883-cf4c-48bc-845c-43f1ccccb88d)
最后提交的时候这样

**Comment by Dt8333** [comment]
请检查你的本地仓库是否包括远程仓库的最新提交[b256d67]
不包括的话请拉取，合并更改，解决冲突后推送。
