### ISSUE TITLE
分数

### ISSUE THREAD

**Issue by hua293** [ANA-Training-2024/setup#8]
没有动test文件，而且所有文件在本地尝试均可运行，但是提交显示0分，能帮忙看看什么原因吗

**Comment by abdtyx** [comment]
你是怎么把整个仓库炸掉重新提交的，原本你的仓库结构应该和student0一样

**Comment by Dt8333** [comment]
请检查您的目录结构是否和student0仓库一致。
如果不一致，请备份您的代码后重新合并仓库。

**Comment by hua293** [comment]
不会呃，捣鼓了一下午，我看提交不上去就直接强制提交了

**Comment by hua293** [comment]
这咋恢复，怎么重新合并

**Comment by abdtyx** [comment]
保存你的代码，从student0拉取代码，然后强制push

**Comment by Dt8333** [comment]
好的
在以下操作前
**先备份代码**
**先备份代码**
**先备份代码**

这里默认您已按照Task 1中相关知识设置本地储存库
首先拉取staff库中的master分支
```bash
git fetch staff master
```

然后使用以下命令来强制恢复到staff/master分支所在的状态
```bash
git reset --hard staff/master
```
**这将覆盖所有已有的更改，请确认做好备份**

然后使用以下命令强制推送以覆盖远程仓库的错误提交
```bash
git push --force
```
**这将覆盖所有远程已有的更改，请确认你清楚自己会覆盖掉什么东西**

然后将自己备份的代码还原到本地仓库对应位置，提交，这时应当能正常推送。
